export enum ErrorCodes {
    DOCUMENT_CREATION_ERROR = 'DOCUMENT_CREATION_ERROR',
    DOCUMENT_UPDATE_ERROR = 'DOCUMENT_UPDATE_ERROR',
    DOCUMENT_DOES_NOT_EXIST_ERROR = 'DOCUMENT_DOES_NOT_EXIST_ERROR',
    DOCUMENT_DELETE_ERROR = 'DOCUMENT_DELETE_ERROR',
    QUERY_ERROR = 'QUERY_ERROR',
    CREATE_TABLE_ERROR = 'CREATE_TABLE_ERROR',
    CREATE_SCHEMA_ERROR = 'CREATE_SCHEMA_ERROR'
}
